const STORE = "docroiAcademicControlCenter.v1";
const today = new Date("2026-07-10T09:00:00");
const eur = new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });
const day = new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "short", year: "numeric" });

const modules = {
  institutions: { title: "Instituciones", singular: "institucion", action: "Nueva institucion", fields: [["name","Nombre","text",1],["type","Tipo","select",1,["Universidad","Escuela de negocio","Empresa","Fundacion","Consultora","Otro"]],["city","Ciudad","text"],["country","Pais","text"],["mode","Modalidad","select",0,["Presencial","Online","Hibrida"]],["web","Web","url"],["notes","Observaciones","textarea"]], cols: ["name","type","city","mode"], filters: ["type","mode"] },
  contacts: { title: "Contactos", singular: "contacto", action: "Nuevo contacto", fields: [["name","Nombre","text",1],["role","Tipo","select",1,["Coordinador academico","Responsable administrativo","Responsable de pagos","Director de programa","Profesor colaborador","Secretaria academica","Otro"]],["position","Cargo","text"],["email","Email","email"],["phone","Telefono","tel"],["institutionId","Institucion","rel:institutions"],["programIds","Programas","multi:programs"],["communication","Comunicacion","text"],["responsibilities","Responsabilidades","textarea"],["notes","Notas","textarea"]], cols: ["name","role","institutionId","email"], filters: ["role","institutionId"] },
  programs: { title: "Programas", singular: "programa", action: "Nuevo programa", fields: [["name","Nombre","text",1],["institutionId","Institucion","rel:institutions",1],["edition","Edicion","text"],["academicYear","Ano academico","text"],["type","Tipo","select",1,["Master","Bootcamp","Asignatura","Modulo","Seminario","Curso in-company","Taller","Otro"]],["status","Estado","select",1,["Previsto","Activo","Finalizado","Cancelado"]],["startDate","Inicio","date"],["endDate","Fin","date"],["mode","Modalidad","select",0,["Presencial","Online","Hibrida"]],["place","Lugar","text"],["onlineLink","Enlace online","url"],["myRole","Mi rol","text"],["academicContactId","Coordinador academico","rel:contacts"],["adminContactId","Responsable administrativo","rel:contacts"],["plannedHours","Horas previstas","number"],["hourlyRate","Precio hora","number"],["manualAmount","Importe pactado","number"],["billingStatus","Facturacion","select",0,["Pendiente de factura","Facturado","No aplica","Cerrado"]],["paymentStatus","Cobro","select",0,["Pendiente","Parcial","Cobrado","Vencido"]],["academicChecklist","Checklist academico","check:academic"],["adminChecklist","Checklist administrativo","check:admin"],["notes","Notas","textarea"]], cols: ["name","institutionId","status","plannedHours","amount"], filters: ["institutionId","status","type","mode"] },
  sessions: { title: "Sesiones", singular: "sesion", action: "Nueva sesion", fields: [["title","Titulo","text",1],["programId","Programa","rel:programs",1],["date","Fecha","date",1],["startTime","Inicio","time"],["endTime","Fin","time"],["duration","Duracion","number"],["mode","Modalidad","select",0,["Presencial","Online","Hibrida"]],["place","Lugar","text"],["classroom","Aula","text"],["onlineLink","Enlace online","url"],["status","Estado","select",1,["Pendiente","Preparada","Impartida","Cancelada","Reprogramada"]],["objectives","Objetivos","textarea"],["topics","Temas","textarea"],["documentIds","Documentos","multi:documents"],["insights","Insights","textarea"],["students","Alumnos relevantes","textarea"],["reminders","Recordatorios","textarea"],["afterNotes","Notas posteriores","textarea"],["tasks","Tareas","textarea"],["evaluationId","Evaluacion","rel:evaluations"],["amount","Importe","number"],["prepChecklist","Checklist","check:session"]], cols: ["title","programId","date","startTime","status"], filters: ["programId","status","mode"] },
  calendar: { title: "Calendario e hitos", singular: "hito", action: "Nuevo hito", fields: [["title","Titulo","text",1],["type","Tipo","select",1,["Clase","Entrega de syllabus","Entrega de documentacion","Examen","Evaluacion","Correccion","Entrega de notas","Emision de factura","Fecha prevista de cobro","Reunion academica","Reunion administrativa","Recordatorio interno","Otro"]],["date","Fecha","date",1],["time","Hora","time"],["programId","Programa","rel:programs"],["institutionId","Institucion","rel:institutions"],["ownerId","Responsable","rel:contacts"],["status","Estado","select",1,["Pendiente","Completado","Vencido","Cancelado"]],["priority","Prioridad","select",0,["Baja","Media","Alta","Critica"]],["notes","Notas","textarea"]], cols: ["title","type","date","priority","status"], filters: ["type","status","priority","programId"] },
  documents: { title: "Documentos", singular: "documento", action: "Nuevo documento", fields: [["name","Nombre","text",1],["type","Tipo","select",1,["Presentacion","Syllabus","Programa academico","Rubrica","Examen","Caso practico","Plantilla","Lectura","Factura","Recibo","Contrato","Documento administrativo","Documento de evaluacion","Otro"]],["fileName","Archivo","file"],["version","Version","text"],["uploadedAt","Subida","date"],["status","Estado","select",1,["Borrador","Pendiente de enviar","Enviado","Aprobado","Sustituido","Archivado"]],["deadline","Fecha limite","date"],["institutionId","Institucion","rel:institutions"],["programId","Programa","rel:programs"],["sessionId","Sesion","rel:sessions"],["evaluationId","Evaluacion","rel:evaluations"],["financeId","Factura o pago","rel:finances"],["ownerId","Responsable","rel:contacts"],["notes","Notas","textarea"]], cols: ["name","type","programId","status","deadline"], filters: ["type","status","institutionId","programId"] },
  evaluations: { title: "Evaluaciones", singular: "evaluacion", action: "Nueva evaluacion", fields: [["name","Nombre","text",1],["programId","Programa","rel:programs",1],["sessionId","Sesion","rel:sessions"],["type","Tipo","select",1,["Examen","Entrega","Rubrica","Caso practico","Proyecto","Notas","Otro"]],["publicationDate","Publicacion","date"],["deliveryDate","Entrega","date"],["correctionDate","Correccion","date"],["gradesDeadline","Limite notas","date"],["status","Estado","select",1,["Pendiente","Publicado","En correccion","Notas entregadas","Cerrado","Vencido"]],["documentId","Documento","rel:documents"],["criteria","Criterios","textarea"],["academicContactId","Responsable academico","rel:contacts"],["checklist","Checklist","check:evaluation"],["notes","Notas","textarea"]], cols: ["name","programId","type","deliveryDate","status"], filters: ["programId","type","status"] },
  finances: { title: "Finanzas", singular: "movimiento", action: "Nuevo ingreso/factura", fields: [["programId","Programa","rel:programs",1],["institutionId","Institucion","rel:institutions"],["concept","Concepto","text",1],["hours","Horas","number"],["hourlyRate","Precio hora","number"],["expectedAmount","Importe previsto","number"],["invoicedAmount","Importe facturado","number"],["collectedAmount","Importe cobrado","number"],["status","Estado","select",1,["Previsto","Pendiente de factura","Facturado","Cobrado parcialmente","Cobrado","Vencido","Cancelado"]],["plannedIssueDate","Emision prevista","date"],["realIssueDate","Emision real","date"],["plannedCollectionDate","Cobro previsto","date"],["realCollectionDate","Cobro real","date"],["adminContactId","Responsable administrativo","rel:contacts"],["invoiceDocumentId","Factura","rel:documents"],["receiptDocumentId","Recibo","rel:documents"],["paymentMethod","Metodo de pago","text"],["notes","Notas","textarea"]], cols: ["concept","programId","status","expectedAmount","collectedAmount","plannedCollectionDate"], filters: ["programId","institutionId","status","adminContactId"] },
  alerts: { title: "Alertas", singular: "alerta", action: "Nueva alerta", fields: [["title","Titulo","text",1],["type","Tipo","select",1,["Documento","Clase","Factura","Cobro","Evaluacion","Administrativo","Recordatorio"]],["date","Fecha","date",1],["status","Estado","select",1,["Proxima","Vencida","Completada","Descartada"]],["priority","Prioridad","select",0,["Baja","Media","Alta","Critica"]],["programId","Programa","rel:programs"],["institutionId","Institucion","rel:institutions"],["ownerId","Responsable","rel:contacts"],["notes","Notas","textarea"]], cols: ["title","type","date","priority","status"], filters: ["type","status","priority","programId"] }
};

const nav = [["dashboard","Dashboard","D"],["institutions","Instituciones","I"],["programs","Programas","P"],["sessions","Sesiones","S"],["calendar","Calendario","C"],["documents","Documentos","D"],["evaluations","Evaluaciones","E"],["finances","Finanzas","EUR"],["contacts","Contactos","C"],["alerts","Alertas","!"],["settings","Configuracion","CFG"]];
const checks = { academic:["Programa recibido","Syllabus entregado","Presentacion preparada","Materiales subidos","Examen definido","Rubrica preparada","Evaluacion publicada","Notas entregadas","Feedback recibido","Cierre academico completado"], admin:["Alta administrativa completada","Datos fiscales enviados","Contrato recibido","Factura emitida","Factura enviada","Pago recibido","Recibo guardado","Cierre economico completado"], session:["Objetivos definidos","Presentacion revisada","Materiales vinculados","Aula/enlace confirmado","Recordatorios enviados","Notas posteriores registradas"], evaluation:["Criterios definidos","Documento preparado","Fecha comunicada","Correccion planificada","Notas entregadas"] };
let state = load();
let route = location.hash.slice(1) || "dashboard";
let activeFilter = null;
let editing = null;

function seed(){
  const institutions=[{id:"ins_horizonte",name:"Universidad Horizonte",type:"Universidad",city:"Madrid",country:"Espana",mode:"Hibrida",web:"https://universidad-horizonte.example",notes:"Prioridad alta por continuidad anual."},{id:"ins_iberica",name:"Iberica Business School",type:"Escuela de negocio",city:"Barcelona",country:"Espana",mode:"Presencial",web:"https://iberica-bs.example",notes:"Programas ejecutivos intensivos."},{id:"ins_nova",name:"NovaHealth Academy",type:"Empresa",city:"Valencia",country:"Espana",mode:"Online",web:"https://novahealth.example",notes:"Formacion in-company para perfiles clinicos."}];
  const contacts=[{id:"con_lucia",name:"Lucia Serrano",role:"Coordinador academico",position:"Coordinadora de master",email:"lucia.serrano@example.com",phone:"+34 600 111 222",institutionId:"ins_horizonte",programIds:["pro_ai_mk"],communication:"Email",responsibilities:"Calendario, syllabus y aula.",notes:"Revisar entregables una semana antes."},{id:"con_mario",name:"Mario Vidal",role:"Responsable administrativo",position:"Administracion academica",email:"mario.vidal@example.com",phone:"+34 600 333 444",institutionId:"ins_horizonte",programIds:["pro_ai_mk"],communication:"Email con copia",responsibilities:"Contratos, facturas y pagos.",notes:"Solicita factura tras cierre de horas."},{id:"con_elena",name:"Elena Prats",role:"Director de programa",position:"Directora executive education",email:"elena.prats@example.com",phone:"+34 600 555 666",institutionId:"ins_iberica",programIds:["pro_roi_exec"],communication:"WhatsApp para urgencias",responsibilities:"Brief y feedback.",notes:"Interes en casos de ROI en salud."},{id:"con_raul",name:"Raul Ortega",role:"Responsable de pagos",position:"Finance partner",email:"raul.ortega@example.com",phone:"+34 600 777 888",institutionId:"ins_nova",programIds:["pro_health_ai"],communication:"Portal proveedor",responsibilities:"Alta proveedor, PO y pagos.",notes:"Pago a 30 dias."}];
  const programs=[{id:"pro_ai_mk",name:"Aplicaciones de IA en Procesos de Marketing",institutionId:"ins_horizonte",edition:"VIII",academicYear:"2026/2027",type:"Master",status:"Activo",startDate:"2026-07-15",endDate:"2026-09-30",mode:"Hibrida",place:"Campus centro",onlineLink:"https://meet.example/ia-marketing",myRole:"Profesor principal",academicContactId:"con_lucia",adminContactId:"con_mario",plannedHours:28,hourlyRate:145,manualAmount:4200,billingStatus:"Pendiente de factura",paymentStatus:"Pendiente",academicChecklist:mkCheck("academic",5),adminChecklist:mkCheck("admin",2),notes:"Enfatizar automatizacion y diagnostico."},{id:"pro_roi_exec",name:"ROI y Decision Comercial para Directivos",institutionId:"ins_iberica",edition:"Open 2026",academicYear:"2026",type:"Seminario",status:"Previsto",startDate:"2026-08-20",endDate:"2026-08-21",mode:"Presencial",place:"Aula executive 3",onlineLink:"",myRole:"Ponente invitado",academicContactId:"con_elena",adminContactId:"con_elena",plannedHours:10,hourlyRate:220,manualAmount:0,billingStatus:"Pendiente de factura",paymentStatus:"Pendiente",academicChecklist:mkCheck("academic",3),adminChecklist:mkCheck("admin",1),notes:"Preparar simulador directivo."},{id:"pro_health_ai",name:"IA Operativa para Equipos Clinicos",institutionId:"ins_nova",edition:"In-company",academicYear:"2026",type:"Curso in-company",status:"Activo",startDate:"2026-06-25",endDate:"2026-07-30",mode:"Online",place:"",onlineLink:"https://teams.example/health-ai",myRole:"Disenador y docente",academicContactId:"con_raul",adminContactId:"con_raul",plannedHours:16,hourlyRate:180,manualAmount:3100,billingStatus:"Facturado",paymentStatus:"Parcial",academicChecklist:mkCheck("academic",7),adminChecklist:mkCheck("admin",5),notes:"Pendiente recibo final."}];
  const sessions=[{id:"ses_001",title:"Mapa de procesos y oportunidades de IA",programId:"pro_ai_mk",date:"2026-07-15",startTime:"16:00",endTime:"19:00",duration:3,mode:"Presencial",place:"Campus centro",classroom:"Aula 204",status:"Preparada",objectives:"Identificar procesos y oportunidades.",topics:"Mapa de procesos, matriz impacto-esfuerzo.",documentIds:["doc_syllabus","doc_presentacion"],insights:"Grupo heterogeneo.",students:"Proyecto e-commerce B2B.",reminders:"Llevar plantilla.",tasks:"Subir caso practico.",amount:435,prepChecklist:mkCheck("session",4)},{id:"ses_002",title:"Casos de automatizacion y diagnostico DocROI",programId:"pro_ai_mk",date:"2026-07-22",startTime:"16:00",endTime:"19:00",duration:3,mode:"Online",onlineLink:"https://meet.example/ia-marketing",status:"Pendiente",objectives:"Construir mini diagnostico.",topics:"KPIs, automatizacion, entregable final.",documentIds:["doc_caso"],reminders:"Enviar enlace 24h antes.",evaluationId:"eva_ia",amount:435,prepChecklist:mkCheck("session",2)},{id:"ses_003",title:"Executive ROI Lab",programId:"pro_roi_exec",date:"2026-08-20",startTime:"09:30",endTime:"14:30",duration:5,mode:"Presencial",place:"Iberica Business School",classroom:"Executive 3",status:"Pendiente",objectives:"Convertir decisiones en mapa ROI.",topics:"Escenarios y sensibilidad.",amount:1100,prepChecklist:mkCheck("session",1)}];
  const documents=[{id:"doc_syllabus",name:"Syllabus IA Marketing 2026",type:"Syllabus",fileName:"syllabus_ia_marketing.pdf",fileData:"",version:"v1.0",uploadedAt:"2026-07-02",status:"Enviado",deadline:"2026-07-08",institutionId:"ins_horizonte",programId:"pro_ai_mk",ownerId:"con_lucia",notes:"Pendiente aprobacion formal."},{id:"doc_presentacion",name:"Presentacion sesion 1",type:"Presentacion",fileName:"docroi_ia_marketing_s1.pptx",fileData:"",version:"v0.9",uploadedAt:"2026-07-09",status:"Pendiente de enviar",deadline:"2026-07-14",institutionId:"ins_horizonte",programId:"pro_ai_mk",sessionId:"ses_001",ownerId:"con_lucia",notes:"Revisar bloque de prompts."},{id:"doc_caso",name:"Caso practico automatizacion",type:"Caso practico",fileName:"caso_automatizacion.docx",fileData:"",version:"v0.4",uploadedAt:"2026-07-10",status:"Borrador",deadline:"2026-07-18",institutionId:"ins_horizonte",programId:"pro_ai_mk",sessionId:"ses_002",evaluationId:"eva_ia",ownerId:"con_lucia",notes:"Falta solucion orientativa."},{id:"doc_factura",name:"Factura parcial NovaHealth",type:"Factura",fileName:"factura_novahealth_junio.pdf",fileData:"",version:"v1.0",uploadedAt:"2026-07-01",status:"Enviado",deadline:"2026-07-01",institutionId:"ins_nova",programId:"pro_health_ai",financeId:"fin_health",ownerId:"con_raul",notes:"Emitida por portal."}];
  const evaluations=[{id:"eva_ia",name:"Entrega mini diagnostico IA",programId:"pro_ai_mk",sessionId:"ses_002",type:"Proyecto",publicationDate:"2026-07-22",deliveryDate:"2026-08-05",correctionDate:"2026-08-08",gradesDeadline:"2026-08-12",status:"Pendiente",documentId:"doc_caso",criteria:"Problema, datos, automatizacion viable, KPI y riesgos.",academicContactId:"con_lucia",checklist:mkCheck("evaluation",2),notes:"Crear rubrica de 10 puntos."},{id:"eva_health",name:"Checklist protocolo IA",programId:"pro_health_ai",type:"Rubrica",publicationDate:"2026-07-18",deliveryDate:"2026-07-24",correctionDate:"2026-07-26",gradesDeadline:"2026-07-29",status:"Publicado",criteria:"Trazabilidad, seguridad e impacto.",academicContactId:"con_raul",checklist:mkCheck("evaluation",3),notes:"Usar feedback cualitativo."}];
  const finances=[{id:"fin_ai",programId:"pro_ai_mk",institutionId:"ins_horizonte",concept:"Docencia master IA Marketing",hours:28,hourlyRate:145,expectedAmount:4200,invoicedAmount:0,collectedAmount:0,status:"Pendiente de factura",plannedIssueDate:"2026-09-30",plannedCollectionDate:"2026-10-30",adminContactId:"con_mario",paymentMethod:"Transferencia",notes:"Emitir al cierre."},{id:"fin_roi",programId:"pro_roi_exec",institutionId:"ins_iberica",concept:"Seminario executive ROI",hours:10,hourlyRate:220,expectedAmount:2200,invoicedAmount:0,collectedAmount:0,status:"Previsto",plannedIssueDate:"2026-08-22",plannedCollectionDate:"2026-09-22",adminContactId:"con_elena",paymentMethod:"Transferencia",notes:"Confirmar PO."},{id:"fin_health",programId:"pro_health_ai",institutionId:"ins_nova",concept:"Curso IA equipos clinicos",hours:16,hourlyRate:180,expectedAmount:3100,invoicedAmount:1800,collectedAmount:900,status:"Cobrado parcialmente",plannedIssueDate:"2026-07-01",realIssueDate:"2026-07-01",plannedCollectionDate:"2026-07-31",realCollectionDate:"2026-07-08",adminContactId:"con_raul",invoiceDocumentId:"doc_factura",paymentMethod:"Transferencia",notes:"Resto previsto a fin de mes."}];
  const calendar=[{id:"cal_1",title:"Clase: mapa de procesos IA",type:"Clase",date:"2026-07-15",time:"16:00",programId:"pro_ai_mk",institutionId:"ins_horizonte",ownerId:"con_lucia",status:"Pendiente",priority:"Alta",notes:"Primera sesion presencial."},{id:"cal_2",title:"Enviar presentacion sesion 1",type:"Entrega de documentacion",date:"2026-07-14",time:"12:00",programId:"pro_ai_mk",institutionId:"ins_horizonte",ownerId:"con_lucia",status:"Pendiente",priority:"Alta",notes:"Enviar version final."},{id:"cal_3",title:"Fecha prevista cobro NovaHealth",type:"Fecha prevista de cobro",date:"2026-07-31",time:"09:00",programId:"pro_health_ai",institutionId:"ins_nova",ownerId:"con_raul",status:"Pendiente",priority:"Alta",notes:"Revisar portal."}];
  const alerts=[{id:"ale_1",title:"Presentacion pendiente de enviar",type:"Documento",date:"2026-07-14",status:"Proxima",priority:"Alta",programId:"pro_ai_mk",institutionId:"ins_horizonte",ownerId:"con_lucia",notes:"Enviar antes de la primera clase."},{id:"ale_2",title:"Caso practico en borrador",type:"Evaluacion",date:"2026-07-18",status:"Proxima",priority:"Media",programId:"pro_ai_mk",institutionId:"ins_horizonte",ownerId:"con_lucia",notes:"Falta solucion orientativa."},{id:"ale_3",title:"Pago parcial NovaHealth",type:"Cobro",date:"2026-07-31",status:"Proxima",priority:"Alta",programId:"pro_health_ai",institutionId:"ins_nova",ownerId:"con_raul",notes:"Reclamar si no entra."}];
  return {institutions,contacts,programs,sessions,calendar,documents,evaluations,finances,alerts,settings:{authMode:"Preparado para autenticacion"}};
}

function mkCheck(type, done=0){return checks[type].map((label,i)=>({label,status:i<done?"Completado":"Pendiente"}));}
function load(){try{return JSON.parse(localStorage.getItem(STORE))||save(seed());}catch{return save(seed());}}
function save(next=state){localStorage.setItem(STORE,JSON.stringify(next));return next;}
function $(s){return document.querySelector(s);} function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));}
function label(mod,id){const x=state[mod]?.find(r=>r.id===id);return x?.name||x?.title||x?.concept||id||"Sin asignar";}
function fmtDate(v){return v?day.format(new Date(v+"T00:00:00")):"Sin fecha";} function diff(v){return v?Math.ceil((new Date(v+"T00:00:00")-new Date(today.toDateString()))/86400000):9999;}
function amount(p){return Number(p.manualAmount||0)||Number(p.plannedHours||0)*Number(p.hourlyRate||0);} function titleOf(r){return r.name||r.title||r.concept||"Registro";}

function render(){renderNav();$("#pageTitle").textContent=route==="dashboard"?"Dashboard":route==="settings"?"Configuracion":modules[route]?.title||"DocROI";document.body.classList.remove("nav-open");route==="dashboard"?dashboard():route==="settings"?settings():moduleView(route);}
function renderNav(){document.querySelector("#mainNav").innerHTML=nav.map(([r,t,i])=>`<a href="#${r}" data-route="${r}" class="${route===r?"active":""}"><span>${i}</span>${t}</a>`).join("");}
function setRoute(r,f=null){route=r;activeFilter=f;location.hash=r;render();}
function kpis(){const expected=sum(state.finances,"expectedAmount"), collected=sum(state.finances,"collectedAmount"), pending=state.finances.reduce((a,x)=>a+Math.max(Number(x.expectedAmount||0)-Number(x.collectedAmount||0),0),0);return [{label:"Proximas clases",value:state.sessions.filter(x=>diff(x.date)>=0&&x.status!=="Cancelada").length,route:"sessions",filter:{date:"future"},hint:"sesiones futuras"},{label:"Clases esta semana",value:state.sessions.filter(x=>diff(x.date)>=0&&diff(x.date)<=7).length,route:"sessions",filter:{date:"week"},hint:"agenda inmediata"},{label:"Programas activos",value:state.programs.filter(x=>x.status==="Activo").length,route:"programs",filter:{status:"Activo"},hint:"en ejecucion"},{label:"Horas previstas",value:sum(state.programs,"plannedHours"),route:"programs",hint:"planificadas"},{label:"Ingresos previstos",value:eur.format(expected),route:"finances",hint:"pipeline"},{label:"Ingresos cobrados",value:eur.format(collected),route:"finances",filter:{status:"Cobrado"},hint:"caja"},{label:"Ingresos pendientes",value:eur.format(pending),route:"finances",filter:{pendingIncome:1},hint:"por cobrar"},{label:"Facturas por emitir",value:state.finances.filter(x=>["Previsto","Pendiente de factura"].includes(x.status)).length,route:"finances",filter:{invoicePending:1},hint:"administrativo"},{label:"Documentos pendientes",value:state.documents.filter(x=>["Borrador","Pendiente de enviar"].includes(x.status)).length,route:"documents",filter:{docPending:1},hint:"materiales"},{label:"Evaluaciones pendientes",value:state.evaluations.filter(x=>!["Notas entregadas","Cerrado"].includes(x.status)).length,route:"evaluations",filter:{evalPending:1},hint:"academico"},{label:"Alertas proximas",value:state.alerts.filter(x=>diff(x.date)>=0&&diff(x.date)<=14&&x.status!=="Completada").length,route:"alerts",filter:{upcoming:1},hint:"14 dias"},{label:"Alertas vencidas",value:state.alerts.filter(x=>x.status==="Vencida"||diff(x.date)<0&&x.status!=="Completada").length,route:"alerts",filter:{overdue:1},hint:"requieren accion"}];}
function dashboard(){const sessions=state.sessions.filter(x=>diff(x.date)>=0).sort(byDate).slice(0,5), docs=state.documents.filter(x=>["Borrador","Pendiente de enviar"].includes(x.status)).sort((a,b)=>(a.deadline||"").localeCompare(b.deadline||"")).slice(0,5), moneyRows=state.finances.filter(x=>!["Cobrado","Cancelado"].includes(x.status)), alerts=state.alerts.filter(x=>x.status!=="Completada").sort(byDate).slice(0,6);$("#app").innerHTML=`<section class="dashboard-hero"><div><p class="eyebrow">Control docente, documental y economico</p><h2>Todo lo que tienes que impartir, entregar y cobrar en una sola cabina.</h2></div><div class="hero-metrics"><span>${state.programs.filter(p=>p.status==="Activo").length} activos</span><span>${eur.format(moneyRows.reduce((a,x)=>a+Math.max(Number(x.expectedAmount||0)-Number(x.collectedAmount||0),0),0))} pendiente</span></div></section><section class="kpi-grid">${kpis().map(k=>`<button class="kpi-card" data-kpi-route="${k.route}" data-kpi-filter='${JSON.stringify(k.filter||{})}'><span>${k.label}</span><strong>${k.value}</strong><small>${k.hint}</small></button>`).join("")}</section><section class="dashboard-grid">${panel("Proximas clases",sessions.map(rowSession).join("")||empty("No hay clases proximas."),"sessions")}${panel("Documentos pendientes",docs.map(rowDoc).join("")||empty("Sin documentos pendientes."),"documents")}${panel("Ingresos y cobros",moneyRows.map(rowFin).join("")||empty("No hay ingresos pendientes."),"finances")}${panel("Alertas",alerts.map(rowAlert).join("")||empty("Sin alertas."),"alerts")}</section>`;}
function panel(t,c,r){return `<article class="panel"><div class="panel-head"><h3>${t}</h3><button class="text-btn" data-route="${r}">Ver todo</button></div><div class="row-list">${c}</div></article>`;} function empty(t){return `<div class="empty-state">${t}</div>`;}
function rowSession(x){return `<button class="list-row" data-detail-module="sessions" data-detail-id="${x.id}"><span><strong>${esc(x.title)}</strong><small>${label("programs",x.programId)} - ${esc(x.mode)}</small></span><em>${fmtDate(x.date)} ${esc(x.startTime||"")}</em></button>`;}
function rowDoc(x){return `<button class="list-row" data-detail-module="documents" data-detail-id="${x.id}"><span><strong>${esc(x.name)}</strong><small>${esc(x.type)} - ${label("programs",x.programId)}</small></span><em>${esc(x.status)}</em></button>`;}
function rowFin(x){return `<button class="list-row" data-detail-module="finances" data-detail-id="${x.id}"><span><strong>${esc(x.concept)}</strong><small>${label("programs",x.programId)} - ${label("contacts",x.adminContactId)}</small></span><em>${eur.format(Math.max(Number(x.expectedAmount||0)-Number(x.collectedAmount||0),0))}</em></button>`;}
function rowAlert(x){return `<button class="list-row" data-detail-module="alerts" data-detail-id="${x.id}"><span><strong>${esc(x.title)}</strong><small>${esc(x.type)} - ${label("programs",x.programId)}</small></span><em>${fmtDate(x.date)}</em></button>`;}

function moduleView(mod){const cfg=modules[mod];if(!cfg)return dashboard();let records=(state[mod]||[]).filter(x=>matchesSearch(mod,x)).filter(x=>matchesFilter(x));$("#app").innerHTML=`<section class="module-head"><div><p class="eyebrow">${records.length} registros</p><h2>${cfg.title}</h2></div><button class="btn primary" data-new="${mod}">${cfg.action}</button></section><section class="filter-bar">${filters(mod)}${activeFilter?`<button class="btn ghost" id="clearFilter">Quitar filtro</button>`:""}</section>${mod==="finances"?financeDash():""}<section class="records-grid ${mod}">${records.length?records.map(x=>card(mod,x)).join(""):empty("No hay registros con estos filtros.")}</section>`;}
function filters(mod){return (modules[mod].filters||[]).map(f=>`<label>${fieldLabel(mod,f)}<select data-filter="${f}"><option value="">Todos</option>${[...new Set((state[mod]||[]).flatMap(x=>x[f]||[]).filter(Boolean))].map(v=>`<option value="${esc(v)}">${display(mod,f,v)}</option>`).join("")}</select></label>`).join("");}
function card(mod,x){const cfg=modules[mod], meta=cfg.cols.filter(k=>!["name","title","concept"].includes(k)).slice(0,4).map(k=>`<span>${fieldLabel(mod,k)}<strong>${value(mod,k,x)}</strong></span>`).join("");return `<article class="record-card"><div class="record-top"><span class="status-pill ${cls(x.status||x.priority)}">${esc(x.status||x.type||"Activo")}</span><button class="icon-btn" data-edit-module="${mod}" data-edit-id="${x.id}" aria-label="Editar">Edit</button></div><h3>${esc(titleOf(x))}</h3><p>${subtitle(mod,x)}</p><div class="meta-grid">${meta}</div>${progress(x)}<div class="card-actions"><button class="btn secondary" data-detail-module="${mod}" data-detail-id="${x.id}">Ver ficha</button></div></article>`;}
function subtitle(mod,x){if(mod==="programs")return `${label("institutions",x.institutionId)} - ${x.type||""} - ${x.myRole||""}`;if(mod==="sessions")return `${label("programs",x.programId)} - ${fmtDate(x.date)} ${x.startTime||""}`;if(mod==="documents")return `${x.type||""} - ${x.fileName||"Sin archivo"} - limite ${fmtDate(x.deadline)}`;if(mod==="finances")return `${label("programs",x.programId)} - pendiente ${eur.format(Math.max(Number(x.expectedAmount||0)-Number(x.collectedAmount||0),0))}`;if(mod==="contacts")return `${x.role||""} - ${label("institutions",x.institutionId)}`;if(mod==="evaluations")return `${label("programs",x.programId)} - entrega ${fmtDate(x.deliveryDate)}`;return `${fmtDate(x.date)} - ${x.priority||"Media"}`;}
function financeDash(){const expected=sum(state.finances,"expectedAmount"), collected=sum(state.finances,"collectedAmount"), overdue=state.finances.filter(x=>x.status==="Vencido"||diff(x.plannedCollectionDate)<0&&!["Cobrado","Cancelado"].includes(x.status)).reduce((a,x)=>a+Math.max(Number(x.expectedAmount||0)-Number(x.collectedAmount||0),0),0), avg=sum(state.finances,"hourlyRate")/Math.max(state.finances.filter(x=>Number(x.hourlyRate)).length,1);return `<section class="finance-strip"><article><span>Previsto</span><strong>${eur.format(expected)}</strong></article><article><span>Cobrado</span><strong>${eur.format(collected)}</strong></article><article><span>Pendiente</span><strong>${eur.format(expected-collected)}</strong></article><article><span>Vencido</span><strong>${eur.format(overdue)}</strong></article><article><span>Precio medio/hora</span><strong>${eur.format(avg)}</strong></article></section>`;}

function openForm(mod,id=""){const cfg=modules[mod], rec=id?state[mod].find(x=>x.id===id):null;editing={mod,id};$("#dialogKicker").textContent=cfg.title;$("#dialogTitle").textContent=id?`Editar ${cfg.singular}`:cfg.action;$("#deleteRecord").hidden=!id;$("#formFields").innerHTML=cfg.fields.map(f=>field(f,rec)).join("");$("#recordDialog").showModal();}
function field([n,l,t,req,opts],rec){const v=rec?.[n]??def(t);const r=req?"required":"";if(t==="textarea")return `<label class="span-2">${l}<textarea name="${n}" rows="3" ${r}>${esc(v)}</textarea></label>`;if(t==="select")return `<label>${l}<select name="${n}" ${r}>${opts.map(o=>`<option ${o===v?"selected":""}>${esc(o)}</option>`).join("")}</select></label>`;if(t.startsWith("rel:")){const m=t.split(":")[1];return `<label>${l}<select name="${n}" ${r}><option value="">Sin asignar</option>${(state[m]||[]).map(x=>`<option value="${x.id}" ${x.id===v?"selected":""}>${esc(titleOf(x))}</option>`).join("")}</select></label>`;}if(t.startsWith("multi:")){const m=t.split(":")[1], sel=Array.isArray(v)?v:[];return `<label class="span-2">${l}<select name="${n}" multiple>${(state[m]||[]).map(x=>`<option value="${x.id}" ${sel.includes(x.id)?"selected":""}>${esc(titleOf(x))}</option>`).join("")}</select><small>Ctrl/Cmd para seleccionar varios.</small></label>`;}if(t.startsWith("check:")){const items=Array.isArray(v)&&v.length?v:mkCheck(t.split(":")[1]);return `<fieldset class="checklist-field span-2" data-check="${n}"><legend>${l}</legend>${items.map((it,i)=>`<label><span>${esc(it.label)}</span><select name="${n}_${i}"><option ${it.status==="Pendiente"?"selected":""}>Pendiente</option><option ${it.status==="Completado"?"selected":""}>Completado</option><option ${it.status==="No aplica"?"selected":""}>No aplica</option></select></label>`).join("")}</fieldset>`;}if(t==="file")return `<label>${l}<input name="${n}" type="file"><small>${esc(v||"Sin archivo")}</small></label>`;return `<label>${l}<input name="${n}" type="${t}" value="${esc(v)}" ${r}></label>`;}
function def(t){return t.startsWith("check:")?mkCheck(t.split(":")[1]):t.startsWith("multi:")?[]:"";}
async function saveForm(e){e.preventDefault();const {mod,id}=editing,cfg=modules[mod],form=e.currentTarget,data=new FormData(form),old=id?state[mod].find(x=>x.id===id):{},rec={...old,id:id||`${mod.slice(0,3)}_${Date.now().toString(36)}`};for(const [n,,t] of cfg.fields){if(t==="file"){const file=data.get(n);if(file&&file.name){rec.fileName=file.name;rec.fileData=await fileData(file);}}else if(t.startsWith("multi:")){rec[n]=[...form.elements[n].selectedOptions].map(o=>o.value);}else if(t.startsWith("check:")){const base=Array.isArray(old[n])&&old[n].length?old[n]:mkCheck(t.split(":")[1]);rec[n]=base.map((it,i)=>({label:it.label,status:data.get(`${n}_${i}`)||"Pendiente"}));}else rec[n]=t==="number"?Number(data.get(n)||0):String(data.get(n)||"").trim();}if(mod==="finances")fillFinance(rec);if(mod==="sessions")fillSession(rec);state[mod]=id?state[mod].map(x=>x.id===id?rec:x):[rec,...state[mod]];save();$("#recordDialog").close();render();}
function fileData(file){return new Promise((ok,ko)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=ko;r.readAsDataURL(file);});}
function fillFinance(r){const p=state.programs.find(x=>x.id===r.programId);if(p){r.institutionId ||= p.institutionId;r.adminContactId ||= p.adminContactId;r.expectedAmount ||= amount(p);}}
function fillSession(r){const p=state.programs.find(x=>x.id===r.programId);if(p){r.mode ||= p.mode;r.place ||= p.place;r.amount ||= Number(r.duration||0)*Number(p.hourlyRate||0);}}
function del(){if(!editing?.id)return;state[editing.mod]=state[editing.mod].filter(x=>x.id!==editing.id);save();$("#recordDialog").close();render();}
function detail(mod,id){const x=state[mod].find(r=>r.id===id);if(!x)return;$("#detailKicker").textContent=modules[mod].title;$("#detailTitle").textContent=titleOf(x);$("#detailContent").innerHTML=`<div class="detail-grid">${modules[mod].fields.map(([n,l,t])=>`<article><span>${l}</span><strong>${detailValue(n,t,x[n],x)}</strong></article>`).join("")}</div>${related(mod,x)}<div class="dialog-actions"><button class="btn primary" data-edit-module="${mod}" data-edit-id="${x.id}">Editar ficha</button></div>`;$("#detailDialog").showModal();}
function related(mod,x){if(mod!=="programs")return"";return `<section class="related-blocks"><article><h3>Sesiones asociadas</h3>${state.sessions.filter(s=>s.programId===x.id).map(rowSession).join("")||empty("Sin sesiones")}</article><article><h3>Documentos asociados</h3>${state.documents.filter(d=>d.programId===x.id).map(rowDoc).join("")||empty("Sin documentos")}</article><article><h3>Finanzas asociadas</h3>${state.finances.filter(f=>f.programId===x.id).map(rowFin).join("")||empty("Sin movimientos")}</article></section>`;}
function detailValue(n,t,v,x){if(t.startsWith("rel:"))return esc(label(t.split(":")[1],v));if(t.startsWith("multi:"))return (v||[]).map(id=>esc(label(t.split(":")[1],id))).join(", ")||"Sin asignar";if(t.startsWith("check:"))return checkHtml(v);if(t==="date")return fmtDate(v);if(t==="file"&&x.fileData)return `<a href="${x.fileData}" download="${esc(x.fileName)}">${esc(x.fileName)}</a>`;if(n.toLowerCase().includes("amount")||n.toLowerCase().includes("rate"))return eur.format(Number(v||0));return esc(Array.isArray(v)?v.join(", "):v||"-");}
function checkHtml(items=[]){return Array.isArray(items)&&items.length?`<ul class="mini-checklist">${items.map(i=>`<li class="${cls(i.status)}"><span>${esc(i.label)}</span><em>${esc(i.status)}</em></li>`).join("")}</ul>`:"Sin checklist";}
function settings(){$("#app").innerHTML=`<section class="settings-grid"><article class="panel"><h2>Privacidad y persistencia</h2><p>La primera version funciona en modo privado local. Los datos se guardan en localStorage y los archivos subidos se conservan como adjuntos codificados.</p><p>La estructura queda preparada para autenticacion, base de datos e integraciones.</p></article><article class="panel"><h2>Futuras mejoras preparadas</h2><div class="tag-cloud">${["Autenticacion","Base de datos","Google Calendar","Google Drive","Gmail","PDF","Excel/CSV","IA para clases","Multiusuario"].map(x=>`<span>${x}</span>`).join("")}</div></article><article class="panel"><h2>Datos demo</h2><p>Incluye instituciones, responsables, programas, sesiones, documentos, evaluaciones, facturas, pagos y alertas ficticias.</p><button class="btn danger" id="hardReset">Restablecer datos semilla</button></article></section>`;}

function sum(a,k){return a.reduce((s,x)=>s+Number(x[k]||0),0);} function byDate(a,b){return (a.date||"").localeCompare(b.date||"");} function cls(s=""){return String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\s+/g,"-");}
function fieldLabel(mod,k){return modules[mod].fields.find(f=>f[0]===k)?.[1]||k;} function display(mod,k,v){const t=modules[mod].fields.find(f=>f[0]===k)?.[2]||"";return t.startsWith("rel:")?label(t.split(":")[1],v):esc(v);} function value(mod,k,x){if(k==="amount")return eur.format(amount(x));const t=modules[mod].fields.find(f=>f[0]===k)?.[2]||"";if(t.startsWith("rel:"))return esc(label(t.split(":")[1],x[k]));if(k.toLowerCase().includes("amount")||k.toLowerCase().includes("rate"))return eur.format(Number(x[k]||0));if(k.toLowerCase().includes("date"))return fmtDate(x[k]);return esc(x[k]??"-");}
function progress(x){const all=["academicChecklist","adminChecklist","prepChecklist","checklist"].flatMap(k=>Array.isArray(x[k])?x[k]:[]);if(!all.length)return"";const done=all.filter(i=>i.status==="Completado").length,p=Math.round(done/all.length*100);return `<div class="progress"><span style="width:${p}%"></span></div><small class="progress-label">${done}/${all.length} checklist completado</small>`;}
function matchesSearch(mod,x){const q=$("#globalSearch")?.value.trim().toLowerCase();return !q||Object.values(x).flat().map(v=>typeof v==="object"?v.label:v).join(" ").toLowerCase().includes(q);} function matchesFilter(x){if(!activeFilter)return true;for(const [k,v] of Object.entries(activeFilter)){if(k==="date"&&v==="future"&&diff(x.date)<0)return false;if(k==="date"&&v==="week"&&!(diff(x.date)>=0&&diff(x.date)<=7))return false;if(k==="pendingIncome"&&!(Math.max(Number(x.expectedAmount||0)-Number(x.collectedAmount||0),0)>0))return false;if(k==="invoicePending"&&!["Previsto","Pendiente de factura"].includes(x.status))return false;if(k==="docPending"&&!["Borrador","Pendiente de enviar"].includes(x.status))return false;if(k==="evalPending"&&["Notas entregadas","Cerrado"].includes(x.status))return false;if(k==="upcoming"&&!(diff(x.date)>=0&&diff(x.date)<=14&&x.status!=="Completada"))return false;if(k==="overdue"&&!(x.status==="Vencida"||diff(x.date)<0&&x.status!=="Completada"))return false;if(!["date","pendingIncome","invoicePending","docPending","evalPending","upcoming","overdue"].includes(k)){const iv=x[k];if(Array.isArray(iv)?!iv.includes(v):String(iv??"")!==String(v))return false;}}return true;}

document.addEventListener("click",e=>{const rb=e.target.closest("[data-route]");if(rb){e.preventDefault();setRoute(rb.dataset.route);}const kb=e.target.closest("[data-kpi-route]");if(kb)setRoute(kb.dataset.kpiRoute,JSON.parse(kb.dataset.kpiFilter||"{}"));const nb=e.target.closest("[data-new]");if(nb)openForm(nb.dataset.new);const eb=e.target.closest("[data-edit-module]");if(eb){$("#detailDialog").close();openForm(eb.dataset.editModule,eb.dataset.editId);}const db=e.target.closest("[data-detail-module]");if(db)detail(db.dataset.detailModule,db.dataset.detailId);if(e.target.id==="clearFilter"){activeFilter=null;render();}if(e.target.id==="hardReset"||e.target.id==="resetSeed"){state=seed();save();render();}});
document.addEventListener("change",e=>{const f=e.target.closest("[data-filter]");if(f){activeFilter=f.value?{[f.dataset.filter]:f.value}:null;render();}});
$("#globalSearch").addEventListener("input",render);$("#recordForm").addEventListener("submit",saveForm);$("#deleteRecord").addEventListener("click",del);$("#cancelDialog").addEventListener("click",()=>$("#recordDialog").close());$("#closeDetail").addEventListener("click",()=>$("#detailDialog").close());$("#menuToggle").addEventListener("click",()=>document.body.classList.toggle("nav-open"));window.addEventListener("hashchange",()=>{route=location.hash.slice(1)||"dashboard";activeFilter=null;render();});
render();
